In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import datetime
from pathlib import Path

In [2]:
file_path = Path("Moneyball.csv")
file_path_salary = Path("2021 MLB Salary Combined.csv")

moneyball_df = pd.read_csv(file_path, index_col = 0)
salary_df = pd.read_csv(file_path_salary, index_col = 0)

moneyball_df.head(20)

                        Real  Predicted
Player
AJ Pollock          0.642333   0.776919
AJ Reed             0.696000   0.804601
Aaron Altherr       0.757000   0.807878
Aaron Hicks         0.586000   0.776919
Aaron Judge         0.637000   0.780002
Abiatal Avelino     0.546000   0.779008
Abraham Almonte     0.637333   0.791819
Abraham Toro        0.802667   0.829960
Adalberto Mondesi   0.845333   0.828573
Adam Duvall         0.712000   0.789838
Adam Eaton          0.598250   0.799437
Adam Engel          0.614667   0.803313
Adam Frazier        0.819333   0.810557
Adam Haseley        0.659333   0.783152
Adam Jones          0.694000   0.796326
Adam Moore          0.790000   0.835315
Adam Rosales        0.614000   0.789700
Addison Russell     0.889000   0.843173
Adeiny Hechavarria  0.727667   0.787606
Adolis Garcia       1.401667   0.848414

In [3]:
salary_df.head()

                    Age Position  ...                  Team  Injured
Player                            ...
Madison Bumgarner    31       SP  ...  Arizona Diamondbacks      NaN
Nick Ahmed           31       SS  ...  Arizona Diamondbacks      NaN
Kole Calhoun         33       RF  ...  Arizona Diamondbacks      NaN
Eduardo Escobar      32       3B  ...  Arizona Diamondbacks      NaN
David Peralta        33       LF  ...  Arizona Diamondbacks      NaN

[5 rows x 12 columns]

In [4]:
salary_df = salary_df.drop(columns = ['Age','Status','Wavier Option', 'Base Salary', 'Signing Bonus', 'Adjusted Salary', 'Payroll %', 'Luxury Tax Salary', 'Injured'])
salary_df.head()

                   Position  Payroll Salary                  Team
Player
Madison Bumgarner        SP        19000000  Arizona Diamondbacks
Nick Ahmed               SS         8125000  Arizona Diamondbacks
Kole Calhoun             RF         8000000  Arizona Diamondbacks
Eduardo Escobar          3B         7666668  Arizona Diamondbacks
David Peralta            LF         7500000  Arizona Diamondbacks

In [5]:
combined_df = pd.concat([moneyball_df, salary_df], axis="columns", join="inner")
combined_df.head(20)

                       Real  Predicted  ... Payroll Salary                   Team
Player                                  ...
Aaron Hicks        0.586000   0.776919  ...       10785714       New York Yankees
Aaron Judge        0.637000   0.780002  ...       10175000       New York Yankees
Abraham Almonte    0.637333   0.791819  ...         990000         Atlanta Braves
Adalberto Mondesi  0.845333   0.828573  ...        2525000     Kansas City Royals
Adam Duvall        0.712000   0.789838  ...        2000000          Miami Marlins
Adam Eaton         0.598250   0.799437  ...         570500     Los Angeles Angels
Adam Engel         0.614667   0.803313  ...        1375000      Chicago White Sox
Adam Frazier       0.819333   0.810557  ...        4300000     Pittsburgh Pirates
Albert Pujols      0.624750   0.791230  ...         570500    Los Angeles Dodgers
Aledmys Diaz       0.721667   0.787568  ...        3000000         Houston Astros
Alex Avila         0.716000   0.776919  ...        1500000   Washington Nationals
Alex Blandino      0.797000   0.816815  ...         573000        Cincinnati Reds
Alex Bregman       0.503667   0.781738  ...       12666666         Houston Astros
Alex Dickerson     0.782500   0.811245  ...        2100000   San Francisco Giants
Alex Kirilloff     0.361000   0.776919  ...         570500        Minnesota Twins
Amed Rosario       0.521000   0.781116  ...        2400000      Cleveland Indians
Andrelton Simmons  0.587333   0.804019  ...       10500000        Minnesota Twins
Andrew Benintendi  0.693333   0.796672  ...        6600000     Kansas City Royals
Andrew Knapp       0.760333   0.805407  ...        1100000  Philadelphia Phillies
Andrew McCutchen   0.749333   0.787463  ...       20000000  Philadelphia Phillies

[20 rows x 5 columns]

In [6]:
expanded_moneyball_df = combined_df
expanded_moneyball_df['OPS Per Millionth Dollar'] = expanded_moneyball_df['Predicted'] / expanded_moneyball_df['Payroll Salary'] * 1000000
expanded_moneyball_df.to_csv(r'expanded moneyball.csv')
expanded_moneyball_df.head(20)

                       Real  ...  OPS Per Millionth Dollar
Player                       ...
Aaron Hicks        0.586000  ...                  0.072032
Aaron Judge        0.637000  ...                  0.076659
Abraham Almonte    0.637333  ...                  0.799817
Adalberto Mondesi  0.845333  ...                  0.328148
Adam Duvall        0.712000  ...                  0.394919
Adam Eaton         0.598250  ...                  1.401292
Adam Engel         0.614667  ...                  0.584227
Adam Frazier       0.819333  ...                  0.188502
Albert Pujols      0.624750  ...                  1.386906
Aledmys Diaz       0.721667  ...                  0.262523
Alex Avila         0.716000  ...                  0.517946
Alex Blandino      0.797000  ...                  1.425506
Alex Bregman       0.503667  ...                  0.061716
Alex Dickerson     0.782500  ...                  0.386307
Alex Kirilloff     0.361000  ...                  1.361821
Amed Rosario       0.521000  ...                  0.325465
Andrelton Simmons  0.587333  ...                  0.076573
Andrew Benintendi  0.693333  ...                  0.120708
Andrew Knapp       0.760333  ...                  0.732188
Andrew McCutchen   0.749333  ...                  0.039373

[20 rows x 6 columns]

In [7]:
expanded_moneyball_df['OPMD'] = expanded_moneyball_df['OPS Per Millionth Dollar']
expanded_moneyball_df = expanded_moneyball_df.drop(columns = 'OPS Per Millionth Dollar')
expanded_moneyball_df.reset_index(inplace=True)
expanded_moneyball_df = expanded_moneyball_df.sort_values(['Position', 'OPMD'], ascending=[True, False]).drop_duplicates(['Position']).reset_index(drop=True)

In [8]:
expanded_moneyball_df

           Player      Real  ...                   Team      OPMD
0   Ronald Guzman  0.636667  ...          Texas Rangers  1.282045
1      Max Moroff  0.858500  ...    St. Louis Cardinals  1.430175
2   Isaac Paredes  0.677500  ...         Detroit Tigers  1.438732
3    P.J. Higgins  0.885000  ...           Chicago Cubs  1.494191
4     Roman Quinn  0.628000  ...  Philadelphia Phillies  1.381616
5   Albert Pujols  0.624750  ...    Los Angeles Dodgers  1.386906
6       Jake Cave  0.859667  ...        Minnesota Twins  1.403417
7     Daz Cameron  0.679500  ...         Detroit Tigers  1.396190
8    Kyle Garlick  0.582333  ...        Minnesota Twins  1.427847
9      Will Smith  0.656333  ...         Atlanta Braves  0.060712
10  Shohei Ohtani  0.699000  ...     Los Angeles Angels  0.264860
11      Gavin Lux  0.962333  ...    Los Angeles Dodgers  1.410609

[12 rows x 7 columns]

In [9]:
expanded_moneyball_df.set_index('Position', inplace=True)

In [10]:
expanded_moneyball_df

                 Player      Real  ...                   Team      OPMD
Position                           ...
1B        Ronald Guzman  0.636667  ...          Texas Rangers  1.282045
2B           Max Moroff  0.858500  ...    St. Louis Cardinals  1.430175
3B        Isaac Paredes  0.677500  ...         Detroit Tigers  1.438732
C          P.J. Higgins  0.885000  ...           Chicago Cubs  1.494191
CF          Roman Quinn  0.628000  ...  Philadelphia Phillies  1.381616
DH        Albert Pujols  0.624750  ...    Los Angeles Dodgers  1.386906
LF            Jake Cave  0.859667  ...        Minnesota Twins  1.403417
OF          Daz Cameron  0.679500  ...         Detroit Tigers  1.396190
RF         Kyle Garlick  0.582333  ...        Minnesota Twins  1.427847
RP/CL        Will Smith  0.656333  ...         Atlanta Braves  0.060712
SP        Shohei Ohtani  0.699000  ...     Los Angeles Angels  0.264860
SS            Gavin Lux  0.962333  ...    Los Angeles Dodgers  1.410609

[12 rows x 6 columns]

In [13]:
expanded_moneyball_df.to_csv('selected_player.csv')